# Generated by Django 4.2.6 on 2023-10-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0002_remove_companies_user_companies_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='updated_at',
        ),
    ]
